import award_types as awards

NORMAL = {awards.CHAIRMANS: 60,
          awards.ENGINEERING_INSPIRATION: 45,
          awards.ROOKIE_ALL_STAR: 25,
          awards.ROOKIE_INSPIRATION: 15,
          awards.ENGINEERING_EXCELLENCE: 20,
          awards.CREATIVITY: 20,
          awards.AUTONOMOUS: 20,
          awards.INNOVATION_IN_CONTROL: 20,
          awards.INDUSTRIAL_DEESIGN: 20,
          awards.QUALITY: 20,
          awards.WOODIE_FLOWERS: 10,
          awards.SPIRIT: 5,
          awards.IMAGERY: 5,
          awards.ENTREPRENEURSHIP: 5,
          awards.GRACIOUS_PROFESSIONALISM: 5,
          awards.JUDGES: 5,
          awards.SAFETY: 5,
          awards.DEANS_LIST: 5,
          awards.HIGHEST_ROOKIE_SEED: 5,
          awards.WINNER: 0,
          awards.FINALIST: 0,
          awards.VOLUNTEER: 0,
          awards.WILDCARD: 0}

CHAMPS = {awards.CHAIRMANS: 20,  # NOTE THIS IS ONLY 20 BECAUSE OF CAF + CCA
          awards.CHAIRMANS_FINALIST: 90,
          awards.ENGINEERING_INSPIRATION: 60,
          awards.ROOKIE_ALL_STAR: 35,
          awards.ROOKIE_INSPIRATION: 20,
          awards.ENGINEERING_EXCELLENCE: 30,
          awards.CREATIVITY: 30,
          awards.AUTONOMOUS: 30,
          awards.INNOVATION_IN_CONTROL: 30,
          awards.INDUSTRIAL_DEESIGN: 30,
          awards.QUALITY: 30,
          awards.WOODIE_FLOWERS: 30,
          awards.DEANS_LIST: 15,
          awards.SPIRIT: 10,
          awards.IMAGERY: 10,
          awards.ENTREPRENEURSHIP: 10,
          awards.GRACIOUS_PROFESSIONALISM: 10,
          awards.JUDGES: 10,
          awards.SAFETY: 10,
          awards.HIGHEST_ROOKIE_SEED: 10,
          awards.WINNER: 0,
          awards.FINALIST: 0,
          awards.VOLUNTEER: 0,
          awards.WILDCARD: 0}
